name: Publish to Maven Central

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: DanySK/build-check-deploy-gradle-action@4.0.1
        with:
          deploy-command: >-
            ./gradlew 
            publishAllPublicationsToProjectLocalRepository 
            zipMavenCentralPortalPublication 
            releaseMavenCentralPortalPublication
          should-deploy: true
          maven-central-username: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
          maven-central-password: ${{ secrets.CENTRAL_PORTAL_TOKEN }}
          signing-key: ${{ secrets.GPG_SIGNING_KEY }}
          signing-password: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}